#ifndef COMX_ADDIN_1f3429f904514646950df8621a840d08_HXX
#define COMX_ADDIN_1f3429f904514646950df8621a840d08_HXX

#ifndef KUL_BITMAP_SAVE_AS
#define KUL_BITMAP_SAVE_AS         (WM_USER + 1)
#endif

#ifndef KUL_BITMAP_MODE
#define KUL_BITMAP_MODE            (WM_USER + 2)
#endif

#ifndef KUL_BITMAP_SETBACKCOLOR
#define KUL_BITMAP_SETBACKCOLOR    (WM_USER + 3)
#endif

#ifndef KUL_BITMAP_SETTRANSPARENT_CLR
#define KUL_BITMAP_SETTRANSPARENT_CLR (WM_USER + 4)
#endif

#ifndef KUL_BITMAP_ENABLETRANSPARENT
#define KUL_BITMAP_ENABLETRANSPARENT (WM_USER + 5)
#endif

#ifndef KUL_MOUSE_MESSAGE
#define KUL_MOUSE_MESSAGE     (WM_USER + 6)
#endif

#ifndef KUL_BITMAP_PAINT_CB
#define KUL_BITMAP_PAINT_CB   (WM_USER + 7)
#endif

#ifndef KUL_FORM_SIZE
#define KUL_FORM_SIZE         (WM_USER + 8)
#endif

#ifndef KUL_SCINTILLA_AUTO_COMPLETE
#define KUL_SCINTILLA_AUTO_COMPLETE (WM_USER + 9)
#endif

#ifndef KUL_SCINTILLA_CALL_TIP
#define KUL_SCINTILLA_CALL_TIP (WM_USER + 10)
#endif

#ifndef KUL_SCINTILLA_AUTO_COMPLETE_SELECT
#define KUL_SCINTILLA_AUTO_COMPLETE_SELECT (WM_USER + 11)
#endif

#ifndef KUL_GL_CANVAS_SENSOR
#define KUL_GL_CANVAS_SENSOR (WM_USER + 15)
#endif

#ifndef KUL_GL_CANVAS_PICKUP_METHOD
#define KUL_GL_CANVAS_PICKUP_METHOD (WM_USER + 16)
#endif

#ifndef KUL_GL_CANVAS_PICKUP_NOTIFY
#define KUL_GL_CANVAS_PICKUP_NOTIFY (WM_USER + 17)
#endif

#ifndef KUL_GL_CANVAS_PICKUP_CB
#define KUL_GL_CANVAS_PICKUP_CB (WM_USER + 18)
#endif

#ifndef KUL_GL_CANVAS_PICKUP_FILTER_CODE
#define KUL_GL_CANVAS_PICKUP_FILTER_CODE (WM_USER + 19)
#endif

#ifndef KUL_GL_CANVAS_PICKUP_PREDEFINE
#define KUL_GL_CANVAS_PICKUP_PREDEFINE (WM_USER + 20)
#endif

#ifndef KUL_GL_CANVAS_PICKUP_LOCK
#define KUL_GL_CANVAS_PICKUP_LOCK (WM_USER + 21)
#endif

#ifndef KUL_GL_CANVAS_PICKUP_LAZY_GROUP
#define KUL_GL_CANVAS_PICKUP_LAZY_GROUP (WM_USER + 22)
#endif

#ifndef KUL_GL_CANVAS_PICKUP_UPDATE_GROUP
#define KUL_GL_CANVAS_PICKUP_UPDATE_GROUP (WM_USER + 23)
#endif

#ifndef KUL_GL_CANVAS_GET_MATRIX
#define KUL_GL_CANVAS_GET_MATRIX (WM_USER + 24)
#endif

#ifndef KUL_GL_CANVAS_SET_MATRIX
#define KUL_GL_CANVAS_SET_MATRIX (WM_USER + 25)
#endif

#ifndef KUL_SHOWTASK 
#define KUL_SHOWTASK (WM_USER + 26)
#endif

#ifndef KUL_HIDEWINDOW
#define KUL_HIDEWINDOW (WM_USER + 27)
#endif

#ifndef KUL_SHOWWINDOW
#define KUL_SHOWWINDOW (WM_USER + 28)
#endif

#ifndef KUL_GL_CANVAS_SINGLE_PICKUP_MODE
#define KUL_GL_CANVAS_SINGLE_PICKUP_MODE (WM_USER + 29)
#endif

//#define KUL_GL_CANVAS_TEXT_OUT (WM_USER + 26)
//#define KUL_GL_CANVAS_TEXT_OUT_CLEAR (WM_USER + 27)

#ifndef KUL_HIGHTLIGHT_SUB_CTRL
#define KUL_HIGHTLIGHT_SUB_CTRL (WM_USER + 257)
#endif

#ifndef KUL_FOCUS_SUB_CTRL
#define KUL_FOCUS_SUB_CTRL (WM_USER + 258)
#endif

#ifndef KUL_PANE_RUN_JS_MSG
#define KUL_PANE_RUN_JS_MSG (WM_USER + 512)
#endif

#ifndef KUL_CHECK_SOCKETIO_CMD_QUEUE
#define KUL_CHECK_SOCKETIO_CMD_QUEUE (WM_USER + 513)
#endif

#ifndef KUL_MODALESS_DIALOG_DESTROY 
#define KUL_MODALESS_DIALOG_DESTROY (WM_USER + 10240)
#endif

#ifndef KUL_UPDATE_FROM_COMMON_AREA 
#define KUL_UPDATE_FROM_COMMON_AREA (WM_USER + 10241)
#endif

#endif
